export const t = {
  // Farben
  bg: '#0a0a0a',
  bgCard: '#111111',
  bgInput: '#1a1a1a',
  red: '#cc0000',
  redDim: '#440000',
  redText: '#ff3333',
  green: '#00aa44',
  greenDim: '#003311',
  border: '#2a2a2a',
  borderRed: '#cc0000',
  textPrimary: '#e0e0e0',
  textDim: '#666666',
  textRed: '#ff3333',

  // Wiederverwendbare Styles
  card: {
    background: '#111111',
    border: '1px solid #2a2a2a',
    borderRadius: '4px',
    padding: '1rem',
    marginBottom: '10px',
  },
  input: {
    width: '100%',
    padding: '10px',
    background: '#1a1a1a',
    border: '1px solid #333',
    borderRadius: '4px',
    color: '#e0e0e0',
    fontSize: '13px',
    marginBottom: '8px',
    boxSizing: 'border-box',
  },
  btnPrimary: {
    padding: '10px 20px',
    background: '#cc0000',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: 'Share Tech Mono, monospace',
    letterSpacing: '0.05em',
  },
  btnGhost: {
    padding: '6px 12px',
    background: 'transparent',
    color: '#666',
    border: '1px solid #333',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '12px',
    fontFamily: 'Share Tech Mono, monospace',
  },
  btnDanger: {
    padding: '4px 10px',
    background: '#440000',
    color: '#ff3333',
    border: '1px solid #cc0000',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '12px',
    fontFamily: 'Share Tech Mono, monospace',
  },
  label: {
    fontSize: '11px',
    color: '#666',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    marginBottom: '6px',
  }
}